neo4j:
  name: "neo4j"
  password: "processingpipeline"
  edition: "community"
  acceptLicenseAgreement: "yes"

image:
  customImage: neo4j:5.13.0

volumes:
  data:
    mode: "defaultStorageClass"
    defaultStorageClass:
      requests:
        storage: 5Gi

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "2000m"
    memory: "4Gi"

services:
  neo4j:
    enabled: true
    type: ClusterIP

env:
  NEO4J_AUTH: "neo4j/processingpipeline"
  NEO4JLABS_PLUGINS: '["graph-data-science"]'
  NEO4J_dbms_security_procedures_unrestricted: "gds.*"
  NEO4J_dbms_security_procedures_allowlist: "gds.*"
  NEO4J_server_memory_pagecache_size: "512M"
  NEO4J_server_memory_heap_initial__size: "512M"
  NEO4J_server_memory_heap_max__size: "1G"